application: hxbana 
version: 1
runtime: python
api_version: 1


handlers:
- url: /template/.*
  script: lib/template.py

- url: /test.*
#  login: admin
  script: lib/gaeunit.py

- url: /_ah/admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /mapreduce(/.*)?
  script: $PYTHON_LIB/google/appengine/ext/mapreduce/main.py
  login: admin

- url: /_ah/info/.*
  script: $PYTHON_LIB/google/appengine/tools/dev_appserver_info
  login: admin

- url: /admin/.*
  script: admin.py

- url: .*
  script: blog.py
